In [1]:
#Q1
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# a) Addition of 2 in all elements
print("a) Addition of 2:", arr + 2)

# b) Multiply 3 with all elements
print("b) Multiplication by 3:", arr * 3)

# c) Divide every element by 2
print("c) Division by 2:", arr / 2)

Original array: [1 2 3 4 5]
a) Addition of 2: [3 4 5 6 7]
b) Multiplication by 3: [ 3  6  9 12 15]
c) Division by 2: [0.5 1.  1.5 2.  2.5]


In [2]:
#Q2
import numpy as np

# a) Reverse the array
arr = np.array([1, 2, 3, 6, 4, 5])
print("a) Reversed array:", arr[::-1])

# b) Most frequent value and indices
# i. x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_freq_x = values[np.argmax(counts)]
indices_x = np.where(x == most_freq_x)[0]
print("b)i. Most frequent value in x:", most_freq_x, "| Indices:", indices_x)

# ii. y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values2, counts2 = np.unique(y, return_counts=True)
most_freq_y = values2[np.argmax(counts2)]
indices_y = np.where(y == most_freq_y)[0]
print("b)ii. Most frequent value in y:", most_freq_y, "| Indices:", indices_y)

a) Reversed array: [5 4 6 3 2 1]
b)i. Most frequent value in x: 1 | Indices: [0 5 7 8 9]
b)ii. Most frequent value in y: 1 | Indices: [0 1 2]


In [3]:
#Q3
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2-D Array:\n", arr)

# a) Access 1st row, 2nd column
print("a) 1st row, 2nd column:", arr[0, 1])

# b) Access 3rd row, 1st column
print("b) 3rd row, 1st column:", arr[2, 0])

2-D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


In [4]:
#Q4
import numpy as np

PridhiThareja = np.linspace(10, 100, 25)
print("Array:", PridhiThareja)

print("Dimensions (ndim):", PridhiThareja.ndim)
print("Shape:", PridhiThareja.shape)
print("Total elements (size):", PridhiThareja.size)
print("Data type (dtype):", PridhiThareja.dtype)
print("Total bytes consumed (nbytes):", PridhiThareja.nbytes)

# reshape() into 5x5 to demonstrate transpose meaningfully
reshaped_arr = PridhiThareja.reshape(5, 5)
print("\nReshaped to 5x5:\n", reshaped_arr)

# Transpose using .T attribute
print("\nTranspose using .T attribute:\n", reshaped_arr.T)

# On the original 1-D array, .T has no visible effect
print("\nOriginal 1-D array's .T shape (unchanged):", PridhiThareja.T.shape)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200

Reshaped to 5x5:
 [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]

Transpose using .T attribute:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]

Original 1-D array's .T shape (unchanged): (25,)


In [5]:
#Q5
import numpy as np

ucs420_PridhiThareja = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])
print("Original array (3x4):\n", ucs420_PridhiThareja)

print("\nMean:", np.mean(ucs420_PridhiThareja))
print("Median:", np.median(ucs420_PridhiThareja))
print("Max:", np.max(ucs420_PridhiThareja))
print("Min:", np.min(ucs420_PridhiThareja))
print("Unique elements:", np.unique(ucs420_PridhiThareja))

# Reshape to 4 rows, 3 columns
reshaped_ucs420_PridhiThareja = ucs420_PridhiThareja.reshape(4, 3)
print("\nReshaped array (4x3):\n", reshaped_ucs420_PridhiThareja)

# Resize to 2 rows, 3 columns
resized_ucs420_PridhiThareja = np.resize(ucs420_PridhiThareja, (2, 3))
print("\nResized array (2x3):\n", resized_ucs420_PridhiThareja)

Original array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2x3):
 [[10 20 30]
 [40 50 60]]
