In [1]:
#Q1 — Sensor Readings

import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2°C to every reading using vectorization
corrected_temp = temperature + 2
print("Corrected Temperatures:", corrected_temp)

# b. Convert Celsius to Fahrenheit
fahrenheit = (9/5) * corrected_temp + 32
print("Fahrenheit:", fahrenheit)

# c. Identify readings greater than 32°C using Boolean indexing
above_32 = corrected_temp[corrected_temp > 32]
print("Readings above 32°C:", above_32)

# d. Count how many readings exceed 32°C
count_above_32 = np.sum(corrected_temp > 32)
print("Count of readings above 32°C:", count_above_32)

# e. Explanation (as a string/print, since it's a written answer)
explanation = """
Vectorization allows NumPy to perform operations on entire arrays at once
using optimized, low-level C code instead of Python's slow for-loops.
Boolean indexing lets us filter elements using a condition applied to the
whole array in one step. Together, they avoid the overhead of looping
through each element individually in Python, making operations on large
datasets significantly faster and more memory-efficient.
"""
print(explanation)

Corrected Temperatures: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings above 32°C: [33 37 40 35 42]
Count of readings above 32°C: 5

Vectorization allows NumPy to perform operations on entire arrays at once 
using optimized, low-level C code instead of Python's slow for-loops. 
Boolean indexing lets us filter elements using a condition applied to the 
whole array in one step. Together, they avoid the overhead of looping 
through each element individually in Python, making operations on large 
datasets significantly faster and more memory-efficient.



In [2]:
#Q2 — Steps Matrix

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Total steps recorded
total_steps = np.sum(steps)
print("Total steps:", total_steps)

# b. Mean number of steps
mean_steps = np.mean(steps)
print("Mean steps:", mean_steps)

# c. Max and min values
max_steps = np.max(steps)
min_steps = np.min(steps)
print("Max steps:", max_steps)
print("Min steps:", min_steps)

# d. Total steps for each day using axis=0 (columns = days)
steps_per_day = np.sum(steps, axis=0)
print("Total steps per day:", steps_per_day)

# e. Total steps for each user using axis=1 (rows = users)
steps_per_user = np.sum(steps, axis=1)
print("Total steps per user:", steps_per_user)

# f. Position of max steps using argmax()
max_position_flat = np.argmax(steps)
max_position_2d = np.unravel_index(max_position_flat, steps.shape)
print("Flat index of max value:", max_position_flat)
print("User/Day position of max value (row, col):", max_position_2d)

Total steps: 84200
Mean steps: 7016.666666666667
Max steps: 9500
Min steps: 4500
Total steps per day: [26500 27300 30400]
Total steps per user: [18300 24500 14400 27000]
Flat index of max value: 11
User/Day position of max value (row, col): (np.int64(3), np.int64(2))


In [3]:
#Q3 — Array Manipulation

# a. Create original array
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

# b. Slice from index 1 to 4
subset = original[1:4]
print("Subset:", subset)

# c. Modify first element of subset to 999
subset[0] = 999
print("After modifying subset -> Original:", original)
print("After modifying subset -> Subset:", subset)
# Note: since slicing creates a VIEW, modifying subset also changes original

# Reset original for clarity in next steps
original = np.array([1, 2, 3, 4, 5, 6])

# d. Slice using .copy(), modify first element to 500
subset_copy = original[1:4].copy()
subset_copy[0] = 500
print("After modifying copy -> Original:", original)
print("After modifying copy -> Copy:", subset_copy)
# Note: .copy() creates a completely separate array, so original is unaffected

# e. Create array 1–12 and reshape into 3x4
matrix = np.arange(1, 13).reshape(3, 4)
print("3x4 Matrix:\n", matrix)

# f. Indexing and slicing
first_row = matrix[0, :]
last_row = matrix[-1, :]
second_column = matrix[:, 1]
sub_block = matrix[0:2, 1:3]  # rows 1-2, columns 2-3 (0-indexed: rows 0-1, cols 1-2)

print("First row:", first_row)
print("Last row:", last_row)
print("Second column:", second_column)
print("Rows 1-2, Columns 2-3:\n", sub_block)

# g. Flatten using flatten() and ravel()
flattened = matrix.flatten()
raveled = matrix.ravel()
print("Flattened (flatten()):", flattened)
print("Flattened (ravel()):", raveled)

# h. Modify an element from ravel() output
raveled[0] = 1000
print("After modifying ravel() output -> Original matrix:\n", matrix)
# Note: ravel() returns a VIEW when possible, so original matrix changes too

# Reset matrix
matrix = np.arange(1, 13).reshape(3, 4)
flattened = matrix.flatten()

# i. Modify an element from flatten() output
flattened[0] = 2000
print("After modifying flatten() output -> Original matrix:\n", matrix)
# Note: flatten() always returns a COPY, so original matrix is unaffected

# j. Shape, ndim, size, dtype
print("Shape:", matrix.shape)
print("Ndim:", matrix.ndim)
print("Size:", matrix.size)
print("Dtype:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4]
After modifying subset -> Original: [  1 999   3   4   5   6]
After modifying subset -> Subset: [999   3   4]
After modifying copy -> Original: [1 2 3 4 5 6]
After modifying copy -> Copy: [500   3   4]
3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, Columns 2-3:
 [[2 3]
 [6 7]]
Flattened (flatten()): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Flattened (ravel()): [ 1  2  3  4  5  6  7  8  9 10 11 12]
After modifying ravel() output -> Original matrix:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
After modifying flatten() output -> Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Ndim: 2
Size: 12
Dtype: int64


In [4]:
#Q4 — Cognitive-Assistive System (Linear Regression via OLS)

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# a. Shape and dimensions of X
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

# b. Transpose of X
X_T = X.T
print("X Transpose:\n", X_T)
print("The transpose flips rows into columns — now each row represents a "
      "feature (sleep, activity, stress) and each column represents a user.")

# c. Matrix product: X.T @ X
XtX = X_T @ X
print("X.T @ X:\n", XtX)

# d. Matrix inverse
XtX_inv = np.linalg.inv(XtX)
print("Inverse of (X.T @ X):\n", XtX_inv)

# e. Ordinary Least Squares: beta = (X^T X)^-1 X^T y
beta = XtX_inv @ X_T @ y
print("Coefficients (beta):", beta)

# f. Interpretation
interpretation = """
Each coefficient in beta represents how much the predicted assistance score
changes for a one-unit increase in that feature, holding the other features
constant. beta[0] corresponds to sleep hours, beta[1] to activity level,
and beta[2] to stress level. A positive coefficient means the feature
increases the assistance score, while a negative coefficient means it
decreases it.
"""
print(interpretation)

# g. Predict for new user
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted assistance score for new user:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
X Transpose:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
The transpose flips rows into columns — now each row represents a feature (sleep, activity, stress) and each column represents a user.
X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of (X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients (beta): [-0.15921454  0.14083853 10.06302242]

Each coefficient in beta represents how much the predicted assistance score 
changes for a one-unit increase in that feature, holding the other features 
constant. beta[0] corresponds to sleep hours, beta[1] to activity level, 
and beta[2] to stress level. A positive coefficient means the feature 
increases the assistance score, while a negative coefficient means it 
decreases it.

Predicted assistance score for new user: 75.27862544779117
